<?php

namespace JD\JdUsercentricsConfigurator\ViewHelper\Video;

use JD\JdUsercentricsConfigurator\Services\HTMLParseService;
use JD\JdUsercentricsConfigurator\Services\UsercentricsConfigurationService;

/**
 * Class EmbedIframeViewHelper
 *
 * This ViewHelper can be used to check an HTML string for YouTube or Vimeo iframe integration by HTML element.
 *
 * @package JD\JdUsercentricsConfigurator\ViewHelper\Video
 * @author Johannes Delesky, Developer
 */
class EmbedIframeViewHelper extends \TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper
{
    /**
     * {@inheritDoc}
     */
    public function initializeArguments()
    {
        parent::initializeArguments(); // TODO: Change the autogenerated stub
        $this->registerArgument('html', 'string', 'A string of an iframe', TRUE);
    }

    /**
     * {@inheritDoc}
     */
    public function render()
    {
        $usercentricsConfiguration = UsercentricsConfigurationService::getUsercentricsConfigForRootPage(
            $GLOBALS['TSFE']->site->getRootPageId()
        );
        if ((bool)$$usercentricsConfiguration['activate'] === TRUE && !empty($$usercentricsConfiguration['settings_id'])) {
            return HTMLParseService::checkHtmlElementContent($this->arguments['html']);
        }

        return $this->arguments['html'];
    }
}